# -*- coding: utf-8 -*-
"""데이터전처리.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts6aCWUR5C0ncIH3xOK79xcmO0qlY_e4
"""

import pandas as pd
import requests
import time
from tqdm import tqdm

# =========================
# 1. 설정
# =========================

API_KEY = "devU01TX0FVVEgyMDI2MDgyNTIyMDAwODEyMDEyOTI="

INPUT_FILE = "서울시_문화공간.csv"
OUTPUT_FILE = "서울시_문화공간_주소변환.csv"

ADDRESS_COLUMN = "주소"


# =========================
# 2. 주소 검색 함수
# =========================

def search_address(address):

    url = "https://business.juso.go.kr/addrlink/addrLinkApi.do"

    params = {
        "confmKey": API_KEY,
        "currentPage": 1,
        "countPerPage": 1,
        "keyword": address,
        "hstryYn": "N",
        "resultType": "json"
    }

    response = requests.get(
        url,
        params=params,
        timeout=10
    )

    data = response.json()

    common = data["results"]["common"]

    # 검색 실패
    if common["errorCode"] != "0":
        return None

    if common["totalCount"] == "0":
        return None

    # 검색 결과
    result = data["results"]["juso"][0]

    return {
        "도로명주소": result.get("roadAddr", ""),
        "지번주소": result.get("jibunAddr", ""),
        "법정동코드": result.get("admCd", ""),
        "법정동명": result.get("emdNm", ""),
        "우편번호": result.get("zipNo", "")
    }


# =========================
# 3. CSV 읽기
# =========================


# df = pd.read_csv(
#     INPUT_FILE,
#     encoding="cp949"
# )

# df = pd.read_csv(
#     INPUT_FILE,
#     encoding="utf-8-sig"
# )

file_path = '/content/drive/My Drive/서울시_문화공간.csv'
df = pd.read_csv(file_path, encoding='cp949')

print(f"총 {len(df)}개의 주소를 처리합니다.")


# =========================
# 4. 주소 하나씩 API 조회
# =========================

results = []

for address in tqdm(
    df[ADDRESS_COLUMN],
    total=len(df)
):

    # 주소가 비어있는 경우
    if pd.isna(address) or str(address).strip() == "":

        results.append({
            "도로명주소": "",
            "지번주소": "",
            "법정동코드": "",
            "법정동명": "",
            "우편번호": "",
            "처리상태": "주소없음"
        })

        continue

    try:

        result = search_address(str(address))

        if result:

            result["처리상태"] = "성공"

        else:

            result = {
                "도로명주소": "",
                "지번주소": "",
                "법정동코드": "",
                "법정동명": "",
                "우편번호": "",
                "처리상태": "검색실패"
            }

    except Exception as e:

        result = {
            "도로명주소": "",
            "지번주소": "",
            "법정동코드": "",
            "법정동명": "",
            "우편번호": "",
            "처리상태": f"오류: {e}"
        }

    results.append(result)

    # API에 너무 빠르게 요청하지 않도록 잠시 대기
    time.sleep(0.1)


# =========================
# 5. 결과 합치기
# =========================

result_df = pd.DataFrame(results)

final_df = pd.concat(
    [
        df.reset_index(drop=True),
        result_df.reset_index(drop=True)
    ],
    axis=1
)


# =========================
# 6. CSV 저장
# =========================

final_df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("완료!")
print(f"결과 파일: {OUTPUT_FILE}")



from google.colab import drive
drive.mount('/content/drive')



import pandas as pd

# -------------------------
# 파일 이름
# -------------------------

# CULTURE_FILE = "서울시_문화공간_주소변환.csv"
# MAPPING_FILE = "주민등록주소코드.xlsx"

OUTPUT_FILE = "/content/drive/My Drive/서울시_문화공간_행정동완료.csv"

CULTURE_FILE = "/content/drive/My Drive/서울시_문화공간_주소변환.csv"
MAPPING_FILE = "/content/drive/My Drive/주민등록주소코드.xlsx"

# -------------------------
# 1. 문화공간 데이터 읽기
# -------------------------

culture = pd.read_csv(
    CULTURE_FILE,
    encoding="utf-8-sig"
)


# -------------------------
# 2. 법정동-행정동 매핑 파일 읽기
# -------------------------

mapping = pd.read_excel(
    MAPPING_FILE
)


# -------------------------
# 3. 코드 형식을 문자열로 통일
# -------------------------

culture["법정동코드"] = (
    pd.to_numeric(culture["법정동코드"], errors="coerce")
    .astype("Int64")
    .astype(str)
)

mapping["법정동코드"] = (
    pd.to_numeric(mapping["법정동코드"], errors="coerce")
    .astype("Int64")
    .astype(str)
)


# -------------------------
# 4. 법정동코드로 매칭
# -------------------------

result = culture.merge(
    mapping[
        [
            "법정동코드",
            "행정동코드",
            "읍면동명"
        ]
    ],
    on="법정동코드",
    how="left"
)


# -------------------------
# 5. 컬럼 이름 변경
# -------------------------

result = result.rename(
    columns={
        "읍면동명": "행정동명"
    }
)


# -------------------------
# 6. 저장
# -------------------------

result.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("완료!")
print(f"저장 파일: {OUTPUT_FILE}")

print(
    result[
        [
            "주소",
            "법정동코드",
            "법정동명",
            "행정동코드",
            "행정동명"
        ]
    ].head()
)





import pandas as pd
import requests
import time
from tqdm import tqdm

# =========================
# 1. 설정
# =========================

API_KEY = "devU01TX0FVVEgyMDI2MDgyNTIyMDAwODEyMDEyOTI="

INPUT_FILE = "/content/drive/My Drive/복지시설.csv"
OUTPUT_FILE = "/content/drive/My Drive/복지시설_주소변환.csv"

ADDRESS_COLUMN = "주소"


# =========================
# 2. 주소 검색 함수
# =========================

def search_address(address):

    url = "https://business.juso.go.kr/addrlink/addrLinkApi.do"

    params = {
        "confmKey": API_KEY,
        "currentPage": 1,
        "countPerPage": 1,
        "keyword": address,
        "hstryYn": "N",
        "resultType": "json"
    }

    response = requests.get(
        url,
        params=params,
        timeout=10
    )

    data = response.json()

    common = data["results"]["common"]

    # 검색 실패
    if common["errorCode"] != "0":
        return None

    if common["totalCount"] == "0":
        return None

    # 검색 결과
    result = data["results"]["juso"][0]

    return {
        "도로명주소": result.get("roadAddr", ""),
        "지번주소": result.get("jibunAddr", ""),
        "법정동코드": result.get("admCd", ""),
        "법정동명": result.get("emdNm", ""),
        "우편번호": result.get("zipNo", "")
    }


# =========================
# 3. CSV 읽기
# =========================


# df = pd.read_csv(
#     INPUT_FILE,
#     encoding="cp949"
# )

df = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8-sig"
)

# file_path = '/content/drive/My Drive/서울시_문화공간.csv'
# df = pd.read_csv(file_path, encoding='cp949')

print(f"총 {len(df)}개의 주소를 처리합니다.")


# =========================
# 4. 주소 하나씩 API 조회
# =========================

results = []

for address in tqdm(
    df[ADDRESS_COLUMN],
    total=len(df)
):

    # 주소가 비어있는 경우
    if pd.isna(address) or str(address).strip() == "":

        results.append({
            "도로명주소": "",
            "지번주소": "",
            "법정동코드": "",
            "법정동명": "",
            "우편번호": "",
            "처리상태": "주소없음"
        })

        continue

    try:

        result = search_address(str(address))

        if result:

            result["처리상태"] = "성공"

        else:

            result = {
                "도로명주소": "",
                "지번주소": "",
                "법정동코드": "",
                "법정동명": "",
                "우편번호": "",
                "처리상태": "검색실패"
            }

    except Exception as e:

        result = {
            "도로명주소": "",
            "지번주소": "",
            "법정동코드": "",
            "법정동명": "",
            "우편번호": "",
            "처리상태": f"오류: {e}"
        }

    results.append(result)

    # API에 너무 빠르게 요청하지 않도록 잠시 대기
    time.sleep(0.1)


# =========================
# 5. 결과 합치기
# =========================

result_df = pd.DataFrame(results)

final_df = pd.concat(
    [
        df.reset_index(drop=True),
        result_df.reset_index(drop=True)
    ],
    axis=1
)


# =========================
# 6. CSV 저장
# =========================

final_df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("완료!")
print(f"결과 파일: {OUTPUT_FILE}")



import pandas as pd # ==================================================행정동 코드 중복 발생

# -------------------------
# 파일 이름
# -------------------------


OUTPUT_FILE = "/content/drive/My Drive/복지시설_행정동완료.csv"

CULTURE_FILE = "/content/drive/My Drive/복지시설_주소변환.csv"
MAPPING_FILE = "/content/drive/My Drive/주민등록주소코드.xlsx"

# -------------------------
# 1. 문화공간 데이터 읽기
# -------------------------

culture = pd.read_csv(
    CULTURE_FILE,
    encoding="utf-8-sig"
)


# -------------------------
# 2. 법정동-행정동 매핑 파일 읽기
# -------------------------

mapping = pd.read_excel(
    MAPPING_FILE
)


# -------------------------
# 3. 코드 형식을 문자열로 통일
# -------------------------

culture["법정동코드"] = (
    pd.to_numeric(culture["법정동코드"], errors="coerce")
    .astype("Int64")
    .astype(str)
)

mapping["법정동코드"] = (
    pd.to_numeric(mapping["법정동코드"], errors="coerce")
    .astype("Int64")
    .astype(str)
)


# -------------------------
# 4. 법정동코드로 매칭
# -------------------------

result = culture.merge(
    mapping[
        [
            "법정동코드",
            "행정동코드",
            "읍면동명"
        ]
    ],
    on="법정동코드",
    how="left"
)


# -------------------------
# 5. 컬럼 이름 변경
# -------------------------

result = result.rename(
    columns={
        "읍면동명": "행정동명"
    }
)


# -------------------------
# 6. 저장
# -------------------------

result.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print("완료!")
print(f"저장 파일: {OUTPUT_FILE}")

print(
    result[
        [
            "주소",
            "법정동코드",
            "법정동명",
            "행정동코드",
            "행정동명"
        ]
    ].head()
)



import pandas as pd
import geopandas as gpd

# =========================
# 파일 설정
# =========================

CSV_FILE = "/content/drive/My Drive/복지시설.csv"

# 실제 SHP 파일 이름으로 수정
SHP_FILE = "/content/drive/My Drive/행정동경계/행정동.csv"

OUTPUT_FILE = "/content/drive/My Drive/복지시설_행정동완료.csv"


# =========================
# 1. 복지시설 CSV 읽기
# =========================

df = pd.read_csv(
    CSV_FILE,
    encoding="utf-8-sig"
)

print("복지시설:", len(df), "개")


# =========================
# 2. 위도/경도 숫자로 변환
# =========================

df["latitude"] = pd.to_numeric(
    df["latitude"],
    errors="coerce"
)

df["longtitude"] = pd.to_numeric(
    df["longtitude"],
    errors="coerce"
)


# =========================
# 3. 좌표가 없는 데이터 확인
# =========================

print(
    "좌표 없음:",
    df["latitude"].isna().sum()
)


# =========================
# 4. 위도/경도를 공간 데이터로 변환
# =========================

points = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(
        df["longtitude"],
        df["latitude"]
    ),
    crs="EPSG:4326"
)


# =========================
# 5. 서울시 행정동 경계 읽기
# =========================

dong = gpd.read_file(
    SHP_FILE
)

print("행정동 경계:", len(dong), "개")

print("\n행정동 경계 컬럼:")
print(dong.columns.tolist())


# =========================
# 6. 좌표계를 행정동 경계와 동일하게 변환
# =========================

points = points.to_crs(
    dong.crs
)


# =========================
# 7. 공간 JOIN
# =========================

result = gpd.sjoin(
    points,
    dong,
    how="left",
    predicate="within"
)


# =========================
# 8. 행정동 코드/이름 확인
# =========================

print("\n결과 컬럼:")
print(result.columns.tolist())


# =========================
# 9. 필요한 컬럼만 정리
# =========================

# 서울시 행정동 SHP의 실제 컬럼명이
# ADSTRD_CD / ADSTRD_NM이라면 사용

result = result.rename(
    columns={
        "ADSTRD_CD": "행정동코드",
        "ADSTRD_NM": "행정동명_공간매칭"
    }
)


# =========================
# 10. 기존 행정동명과 구분
# =========================

# 기존 CSV의 행정동명은 그대로 두고
# 공간좌표로 새롭게 찾은 행정동을 저장


# =========================
# 11. geometry 제거
# =========================

result = result.drop(
    columns=["geometry", "index_right"],
    errors="ignore"
)


# =========================
# 12. CSV 저장
# =========================

result.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


# =========================
# 13. 결과 확인
# =========================

print("\n======================")
print("완료!")
print("======================")

print("원본:", len(df))
print("결과:", len(result))

success = result["행정동코드"].notna().sum()

print("매칭 성공:", success)
print("매칭 실패:", len(result) - success)

print("\n결과:")
print(
    result[
        [
            "시설 이름",
            "주소",
            "latitude",
            "longtitude",
            "행정동코드",
            "행정동명_공간매칭"
        ]
    ].head(20)
)



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import geopandas as gpd

# ==================================
# 파일명
# ==================================

INPUT_FILE = "/content/drive/My Drive/서울시_문화공간_주소변환.csv"
DONG_FILE = "/content/drive/My Drive/서울시_상권분석서비스_영역_행정동.csv"
OUTPUT_FILE = "/content/drive/My Drive/문화시설_정제.csv"


# ==============================
# 1. 문화시설 CSV
# ==============================

df = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8-sig"
)

print("원본 시설 행:", len(df))


# ==============================
# 2. 위도 / 경도 숫자로 변환
# ==============================

df["위도"] = pd.to_numeric(
    df["위도"],
    errors="coerce"
)

df["경도"] = pd.to_numeric(
    df["경도"],
    errors="coerce"
)


# ==============================
# 3. 좌표가 없는 행 확인
# ==============================

print("위도 없음:", df["위도"].isna().sum())
print("경도 없음:", df["경도"].isna().sum())


# ==============================
# 4. 위도/경도를 공간 데이터로 변환
# ==============================

facilities = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(
        df["경도"],
        df["위도"]
    ),
    crs="EPSG:4326"
)


# ==============================
# 5. 서울시 행정동 대표좌표
# ==============================

# dong = pd.read_csv(
#     DONG_FILE,
#     encoding="utf-8-sig"
# )

dong = pd.read_csv(
    DONG_FILE,
    encoding="cp949"
)

print("행정동 데이터:", len(dong))


# ==============================
# 6. 행정동 대표좌표 생성
# ==============================

dong_geo = gpd.GeoDataFrame(
    dong,
    geometry=gpd.points_from_xy(
        dong["엑스좌표_값"],
        dong["와이좌표_값"]
    ),
    crs="EPSG:5181"
)


# ==============================
# 7. 시설 좌표를 서울시 좌표계로 변환
# ==============================

facilities = facilities.to_crs(
    "EPSG:5181"
)


# ==============================
# 8. 가장 가까운 행정동 찾기
# ==============================

matched = gpd.sjoin_nearest(
    facilities,
    dong_geo[
        [
            "행정동_코드",
            "행정동_명",
            "geometry"
        ]
    ],
    how="left",
    distance_col="행정동_거리_m"
)


# ==============================
# 9. 행정동 컬럼 이름 변경
# ==============================

matched = matched.rename(
    columns={
        "행정동_코드": "행정동코드",
        "행정동_명": "행정동명"
    }
)


# ==============================
# 10. geometry 제거
# ==============================

matched = matched.d



rop(
    columns=["geometry", "index_right"],
    errors="ignore"
)


# ==============================
# 11. 같은 시설 중복 제거
# ==============================

matched = matched.drop_duplicates(
    subset=["문화시설명", "주소"],
    keep="first"
)


# ==============================
# 12. 저장
# ==============================

matched.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


# ==============================
# 13. 결과 확인
# ==============================

print()
print("======================")
print("완료!")
print("======================")

print("원본 행:", len(df))
print("정제 후:", len(matched))
print("제거된 행:", len(df) - len(matched))

print()
print("결과 일부:")

print(
    matched[
        [
            "문화시설명",
            "주소",
            "위도",
            "경도",
            "행정동코드",
            "행정동명",
            "행정동_거리_m"
        ]
    ].head(20)
)



import pandas as pd
import requests
import time

# =====================================
# 설정
# =====================================

REST_API_KEY = "27c84d3b19df5551d2434cda932d9307"

INPUT_FILE = "/content/drive/My Drive/복지시설_최종.csv"
OUTPUT_FILE = "/content/drive/My Drive/복지시설_카카오완료.csv"

# =====================================
# 카카오 API 주소
# =====================================

ADDRESS_URL = "https://dapi.kakao.com/v2/local/search/address.json"
REGION_URL = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"

headers = {
    "Authorization": f"KakaoAK {REST_API_KEY}"
}

# =====================================
# CSV 읽기
# =====================================

df = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8-sig"
)

print("시설 수:", len(df))

# 결과 컬럼
df["위도"] = ""
df["경도"] = ""
df["행정동코드"] = ""
df["행정동명"] = ""
df["처리상태"] = ""

# =====================================
# 주소 → 위도/경도
# =====================================

for i, row in df.iterrows():

    address = str(row["주소"]).strip()

    if not address or address == "nan":
        df.at[i, "처리상태"] = "주소없음"
        continue

    try:

        # -------------------------------
        # 1. 주소 → 좌표
        # -------------------------------

        response = requests.get(
            ADDRESS_URL,
            headers=headers,
            params={
                "query": address
            },
            timeout=10
        )

        if response.status_code != 200:
            df.at[i, "처리상태"] = (
                f"주소API 오류 {response.status_code}"
            )
            continue

        data = response.json()

        documents = data.get("documents", [])

        if not documents:
            df.at[i, "처리상태"] = "주소검색 실패"
            continue

        # 첫 번째 검색 결과
        result = documents[0]

        longitude = result["x"]
        latitude = result["y"]

        df.at[i, "위도"] = latitude
        df.at[i, "경도"] = longitude

        # -------------------------------
        # 2. 좌표 → 행정동
        # -------------------------------

        response2 = requests.get(
            REGION_URL,
            headers=headers,
            params={
                "x": longitude,
                "y": latitude
            },
            timeout=10
        )

        if response2.status_code != 200:
            df.at[i, "처리상태"] = (
                f"행정동API 오류 {response2.status_code}"
            )
            continue

        data2 = response2.json()

        documents2 = data2.get("documents", [])

        # region_type = H → 행정동
        admin_dong = None

        for region in documents2:
            if region.get("region_type") == "H":
                admin_dong = region
                break

        if admin_dong:

            df.at[i, "행정동코드"] = admin_dong["code"]
            df.at[i, "행정동명"] = admin_dong[
                "region_3depth_name"
            ]

            df.at[i, "처리상태"] = "성공"

        else:
            df.at[i, "처리상태"] = "행정동없음"

    except Exception as e:

        df.at[i, "처리상태"] = f"오류: {e}"

    # API 요청 간격
    time.sleep(0.1)

    # 진행상황
    if (i + 1) % 10 == 0:
        print(f"{i + 1}/{len(df)} 처리 완료")


# =====================================
# 결과 저장
# =====================================

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("==============================")
print("완료!")
print("==============================")

print("원본:", len(df))
print("성공:", (df["처리상태"] == "성공").sum())
print(
    "실패:",
    (df["처리상태"] != "성공").sum()
)

print("저장 파일:", OUTPUT_FILE)



import pandas as pd
import requests
import time

# =====================================
# 설정
# =====================================

REST_API_KEY = "27c84d3b19df5551d2434cda932d9307"

INPUT_FILE = "/content/drive/My Drive/유휴공간_최종.csv"
OUTPUT_FILE = "/content/drive/My Drive/유휴공간_카카오완료.csv"

# =====================================
# 카카오 API 주소
# =====================================

ADDRESS_URL = "https://dapi.kakao.com/v2/local/search/address.json"
REGION_URL = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"

headers = {
    "Authorization": f"KakaoAK {REST_API_KEY}"
}

# =====================================
# CSV 읽기
# =====================================

df = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8-sig"
)

print("시설 수:", len(df))

# 결과 컬럼
df["위도"] = ""
df["경도"] = ""
df["행정동코드"] = ""
df["행정동명"] = ""
df["처리상태"] = ""

# =====================================
# 주소 → 위도/경도
# =====================================

for i, row in df.iterrows():

    address = str(row["주소"]).strip()

    if not address or address == "nan":
        df.at[i, "처리상태"] = "주소없음"
        continue

    try:

        # -------------------------------
        # 1. 주소 → 좌표
        # -------------------------------

        response = requests.get(
            ADDRESS_URL,
            headers=headers,
            params={
                "query": address
            },
            timeout=10
        )

        if response.status_code != 200:
            df.at[i, "처리상태"] = (
                f"주소API 오류 {response.status_code}"
            )
            continue

        data = response.json()

        documents = data.get("documents", [])

        if not documents:
            df.at[i, "처리상태"] = "주소검색 실패"
            continue

        # 첫 번째 검색 결과
        result = documents[0]

        longitude = result["x"]
        latitude = result["y"]

        df.at[i, "위도"] = latitude
        df.at[i, "경도"] = longitude

        # -------------------------------
        # 2. 좌표 → 행정동
        # -------------------------------

        response2 = requests.get(
            REGION_URL,
            headers=headers,
            params={
                "x": longitude,
                "y": latitude
            },
            timeout=10
        )

        if response2.status_code != 200:
            df.at[i, "처리상태"] = (
                f"행정동API 오류 {response2.status_code}"
            )
            continue

        data2 = response2.json()

        documents2 = data2.get("documents", [])

        # region_type = H → 행정동
        admin_dong = None

        for region in documents2:
            if region.get("region_type") == "H":
                admin_dong = region
                break

        if admin_dong:

            df.at[i, "행정동코드"] = admin_dong["code"]
            df.at[i, "행정동명"] = admin_dong[
                "region_3depth_name"
            ]

            df.at[i, "처리상태"] = "성공"

        else:
            df.at[i, "처리상태"] = "행정동없음"

    except Exception as e:

        df.at[i, "처리상태"] = f"오류: {e}"

    # API 요청 간격
    time.sleep(0.1)

    # 진행상황
    if (i + 1) % 10 == 0:
        print(f"{i + 1}/{len(df)} 처리 완료")


# =====================================
# 결과 저장
# =====================================

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("==============================")
print("완료!")
print("==============================")

print("원본:", len(df))
print("성공:", (df["처리상태"] == "성공").sum())
print(
    "실패:",
    (df["처리상태"] != "성공").sum()
)

print("저장 파일:", OUTPUT_FILE)