name: Render Keep-Alive Ping

on:
  schedule:
    - cron: '*/10 22-23 * * *'
    - cron: '*/10 0-14 * * *'

  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render service
        run: |
          echo "Current UTC time:"
          date -u

          echo "Current KST time:"
          TZ=Asia/Seoul date

          echo "Ping Render:"
          curl -i \
            --max-time 180 \
            -H "User-Agent: GitHubActions-KeepAlive/1.0" \
            "https://filltheblank.onrender.com/idle-space-list"
